const express = require('express');
const router = express.Router();

const glossaryTerms = [
  
  { ID:'1' ,Term: 'DevOps',  Description: 'DevOps is a methodology in the software development and IT industry.', Reference: 'Wikipedia Contributors, “DevOps,” Wikipedia, Dec. 01, 2019. https://en.wikipedia.org/wiki/DevOps' },
  { ID:'2' ,Term: 'Microservices',  Description: 'an architectural style that structures an application as a collection of services ', Reference: 'C. Richardson, “Microservices.io,” microservices.io, 2017. https://microservices.io/' },
  { ID:'3' ,Term: 'Version Control',  Description: 'Version control helps developers track and manage changes to a software project’s code. As a software project grows, version control becomes essentia', Reference: 'B. Jackson, “What Is GitHub? A Beginner’s Introduction to...,” Kinsta Managed WordPress Hosting, Apr. 20, 2018. https://kinsta.com/knowledgebase/what-is-github/' },
  { ID:'4' ,Term: 'Azure',  Description: 'Microsoft Azure, often referred to as Azure, is a cloud computing platform run by Microsoft, which offers access, management, and development of applications and services through global data centers.', Reference: 'Wikipedia Contributors, “Microsoft Azure,” Wikipedia, Oct. 12, 2019. https://en.wikipedia.org/wiki/Microsoft_Azure' },
  { ID:'5' ,Term: 'Google Cloud',  Description: 'Google Cloud Platform, offered by Google, is a suite of cloud computing services that runs on the same infrastructure that Google uses internally for its end-user products, such as Google Search, Gmail, Google Drive, and YouTube', Reference:'Wikipedia Contributors, “Google Cloud Platform,” Wikipedia, Oct. 11, 2019. https://en.wikipedia.org/wiki/Google_Cloud_Platform'},
  { ID:'6' ,Term: 'Node JS',  Description: 'Node.js allows developers to create both front-end and back-end applications using JavaScript. It was released in 2009 by Ryan Dahl', Reference: 'B. Semah, “What Exactly is Node.js? Explained for Beginners,” freeCodeCamp.org, Dec. 05, 2022. https://www.freecodecamp.org/news/what-is-node-js/' },
  { ID:'7' ,Term: 'Git',  Description: 'Git is a distributed version control system that tracks changes in any set of computer files, usually used for coordinating work among programmers who are collaboratively developing source code during software development', Reference: 'Wikipedia Contributors, “Git,” Wikipedia, May 12, 2019. https://en.wikipedia.org/wiki/Git' },
  { ID:'8' ,Term: 'VSCode',  Description: 'Visual Studio Code, also commonly referred to as VS Code, is a source-code editor made by Microsoft with the Electron Framework, for Windows, Linux and macOS.', Reference: 'Wikipedia Contributors, “Visual Studio Code,” Wikipedia, Mar. 21, 2019. https://en.wikipedia.org/wiki/Visual_Studio_Code' },
  { ID:'9' ,Term: 'DevOps Cycle',  Description: 'The DevOps lifecycle is a continuous software development process that employs DevOps best practices to plan, build, integrate, deploy, monitor, operate, and offer continuous feedback throughout the softwares lifecycle',Reference:'Wikipedia Contributors, “DevOps,” Wikipedia, Dec. 01, 2019. https://en.wikipedia.org/wiki/DevOps'},
  { ID:'10' ,Term: 'Containers',  Description: 'TesContainers are packages of software that contain all of the necessary elements to run in any environment. In this way, containers virtualize the operating system and run anywhere, from a private data center to the public cloud or even on a developer’s personal laptopt', Reference: 'https://cloud.google.com/learn/what-are-containers' },
  { ID:'11' ,Term: 'Integration Testing',  Description: 'Integration testing (sometimes called integration and testing, abbreviated I&T) is the phase in software testing in which the whole software module is tested or if it consists of multiple software modules they are combined and then tested as a group', Reference: '“Integration testing,” Wikipedia, Dec. 06, 2020. https://en.wikipedia.org/wiki/Integration_testing#:~:text=Integration%20testing%20(sometimes%20called%20integration‌' },
  { ID:'12' ,Term: 'Repository',  Description: ' repository contains all of your project', Reference: '“About repositories,” GitHub Docs. https://docs.github.com/en/repositories/creating-and-managing-repositories/about-repositories‌' },
  { ID:'13' ,Term: 'Infrastructure',  Description: 'Infrastructure is defined as the basic physical systems of a business, region, or nation and often involves the production of public goods or production processes', Reference: '“What Is Infrastructure?,” Investopedia. https://www.investopedia.com/terms/i/infrastructure.asp#:~:text=Infrastructure%20is%20defined%20as%20the ‌' },
  { ID:'14' ,Term: 'Integration',  Description: ' the connection of data, applications, APIs, and devices across your IT organization to be more efficient, productive, and agile.', Reference: '“What is integration?,” www.redhat.com. https://www.redhat.com/en/topics/integration/what-is-integration#:~:text=History%20of%20integration- (accessed Sep. 16, 2023).' },
  { ID:'15' ,Term: 'pipeline',  Description:'In computing, pipeline refers to the logical queue that is filled with all the instructions for the computer processor to process in parallel. It is the process of storing and queuing tasks and instructions that are executed simultaneously by the processor in an organized way.', Reference: '“What is a Pipeline? - Definition from Techopedia,” Techopedia.com. https://www.techopedia.com/definition/5312/pipeline' },
  { ID:'16' ,Term: 'Virtual Machine',  Description:'A Virtual Machine (VM) is a compute resource that uses software instead of a physical computer to run programs and deploy apps. One or more virtual “guest” machines run on a physical “host” machine.  Each virtual machine runs its own operating system and functions separately from the other VMs, even when they are all running on the same host.', Reference: 'https://www.vmware.com/au/topics/glossary/content/virtual-machine.html' },
  { ID:'17' ,Term: 'Declarative programming', Description:'declarative programming consists of instructing a program on what needs to be done, instead of telling it how to do it. ', Reference: '“Declarative Programming: Is It A Real Thing? | Toptal®,” Toptal Engineering Blog. https://www.toptal.com/software/declarative-programming#:~:text=In%20a%20nutshell%2C%20declarative%20programming (accessed Sep. 19, 2023).' },
  { ID:'18' ,Term: 'Docker',  Description: 'Docker is an open source platform that enables developers to build, deploy, run, update and manage containers', Reference: '“What is Docker? | IBM,” www.ibm.com. https://www.ibm.com/topics/docker#:~:text=Docker%20is%20an%20open%20source%20platform%20that%20enables%20developers%20to' },
  { ID:'19' ,Term: 'Scriptting programming',  Description:' A scripting language is a programming language that employs a high-level construct to interpret and execute one command at a time', Reference: '“What is scripting language? - Definition from WhatIs.com,” WhatIs.com. https://www.techtarget.com/whatis/definition/scripting-language#:~:text=A%20scripting%20language%20is%20a‌' },
  { ID:'20' ,Term: 'IAC',  Description:'Infrastructure as code (IaC) is the process of managing and provisioning computer data centers through machine-readable definition files, rather than physical hardware configuration or interactive configuration tools', Reference: '“Infrastructure as code,” Wikipedia, Feb. 18, 2021. https://en.wikipedia.org/wiki/Infrastructure_as_code' },


];

router.get('/', (req, res, next) => {
  res.render('index', { title: 'DevOps Glossary', glossaryTerms });
});

module.exports = router;
