const express = require('express');
const router = express.Router();

const glossaryTerms = [
  
  { ID:'1' ,Term: 'DevOps',  Description: 'DevOps is a methodology in the software development and IT industry.', Reference: 'Wikipedia Contributors, “DevOps,” Wikipedia, Dec. 01, 2019. https://en.wikipedia.org/wiki/DevOps' },
  { ID:'2' ,Term: 'Microservices',  Description: 'an architectural style that structures an application as a collection of services ', Reference: 'C. Richardson, “Microservices.io,” microservices.io, 2017. https://microservices.io/' },
  { ID:'3' ,Term: 'Version Control',  Description: 'Version control helps developers track and manage changes to a software project’s code. As a software project grows, version control becomes essentia', Reference: 'B. Jackson, “What Is GitHub? A Beginner’s Introduction to...,” Kinsta Managed WordPress Hosting, Apr. 20, 2018. https://kinsta.com/knowledgebase/what-is-github/' },
  { ID:'4' ,Term: 'Azure',  Description: 'Microsoft Azure, often referred to as Azure, is a cloud computing platform run by Microsoft, which offers access, management, and development of applications and services through global data centers.', Reference: 'Wikipedia Contributors, “Microsoft Azure,” Wikipedia, Oct. 12, 2019. https://en.wikipedia.org/wiki/Microsoft_Azure' },
  { ID:'5' ,Term: 'Google Cloud',  Description: 'Google Cloud Platform, offered by Google, is a suite of cloud computing services that runs on the same infrastructure that Google uses internally for its end-user products, such as Google Search, Gmail, Google Drive, and YouTube', Reference:'Wikipedia Contributors, “Google Cloud Platform,” Wikipedia, Oct. 11, 2019. https://en.wikipedia.org/wiki/Google_Cloud_Platform'},
  { ID:'6' ,Term: 'Node JS',  Description: 'Node.js allows developers to create both front-end and back-end applications using JavaScript. It was released in 2009 by Ryan Dahl', Reference: 'B. Semah, “What Exactly is Node.js? Explained for Beginners,” freeCodeCamp.org, Dec. 05, 2022. https://www.freecodecamp.org/news/what-is-node-js/' },
  { ID:'7' ,Term: 'Git',  Description: 'Git is a distributed version control system that tracks changes in any set of computer files, usually used for coordinating work among programmers who are collaboratively developing source code during software development', Reference: 'Wikipedia Contributors, “Git,” Wikipedia, May 12, 2019. https://en.wikipedia.org/wiki/Git' },
  { ID:'8' ,Term: 'VSCode',  Description: 'Visual Studio Code, also commonly referred to as VS Code, is a source-code editor made by Microsoft with the Electron Framework, for Windows, Linux and macOS.', Reference: 'Wikipedia Contributors, “Visual Studio Code,” Wikipedia, Mar. 21, 2019. https://en.wikipedia.org/wiki/Visual_Studio_Code' },
  { ID:'9' ,Term: 'DevOps Cycle',  Description: 'The DevOps lifecycle is a continuous software development process that employs DevOps best practices to plan, build, integrate, deploy, monitor, operate, and offer continuous feedback throughout the softwares lifecycle',Reference:'Wikipedia Contributors, “DevOps,” Wikipedia, Dec. 01, 2019. https://en.wikipedia.org/wiki/DevOps'},
  { ID:'10' ,Term: 'Containers',  Description: 'TesContainers are packages of software that contain all of the necessary elements to run in any environment. In this way, containers virtualize the operating system and run anywhere, from a private data center to the public cloud or even on a developer’s personal laptopt', Reference: 'https://cloud.google.com/learn/what-are-containers' },
  { ID:'11' ,Term: 'Integration Testing',  Description: 'Integration testing (sometimes called integration and testing, abbreviated I&T) is the phase in software testing in which the whole software module is tested or if it consists of multiple software modules they are combined and then tested as a group', Reference: '“Integration testing,” Wikipedia, Dec. 06, 2020. https://en.wikipedia.org/wiki/Integration_testing#:~:text=Integration%20testing%20(sometimes%20called%20integration‌' },
  { ID:'12' ,Term: 'Repository',  Description: ' repository contains all of your project', Reference: '“About repositories,” GitHub Docs. https://docs.github.com/en/repositories/creating-and-managing-repositories/about-repositories‌' },
  { ID:'13' ,Term: 'Infrastructure',  Description: 'Infrastructure is defined as the basic physical systems of a business, region, or nation and often involves the production of public goods or production processes', Reference: '“What Is Infrastructure?,” Investopedia. https://www.investopedia.com/terms/i/infrastructure.asp#:~:text=Infrastructure%20is%20defined%20as%20the ‌' },
  { ID:'14' ,Term: 'Integration',  Description: ' the connection of data, applications, APIs, and devices across your IT organization to be more efficient, productive, and agile.', Reference: '“What is integration?,” www.redhat.com. https://www.redhat.com/en/topics/integration/what-is-integration#:~:text=History%20of%20integration- (accessed Sep. 16, 2023).' },
  { ID:'15' ,Term: 'pipeline',  Description:'In computing, pipeline refers to the logical queue that is filled with all the instructions for the computer processor to process in parallel. It is the process of storing and queuing tasks and instructions that are executed simultaneously by the processor in an organized way.', Reference: '“What is a Pipeline? - Definition from Techopedia,” Techopedia.com. https://www.techopedia.com/definition/5312/pipeline' },
  { ID:'16' ,Term: 'Virtual Machine',  Description:'A Virtual Machine (VM) is a compute resource that uses software instead of a physical computer to run programs and deploy apps. One or more virtual “guest” machines run on a physical “host” machine.  Each virtual machine runs its own operating system and functions separately from the other VMs, even when they are all running on the same host.', Reference: 'https://www.vmware.com/au/topics/glossary/content/virtual-machine.html' },
  { ID:'17' ,Term: 'Declarative programming', Description:'declarative programming consists of instructing a program on what needs to be done, instead of telling it how to do it. ', Reference: '“Declarative Programming: Is It A Real Thing? | Toptal®,” Toptal Engineering Blog. https://www.toptal.com/software/declarative-programming#:~:text=In%20a%20nutshell%2C%20declarative%20programming (accessed Sep. 19, 2023).' },
  { ID:'18' ,Term: 'Docker',  Description: 'Docker is an open source platform that enables developers to build, deploy, run, update and manage containers', Reference: '“What is Docker? | IBM,” www.ibm.com. https://www.ibm.com/topics/docker#:~:text=Docker%20is%20an%20open%20source%20platform%20that%20enables%20developers%20to' },
  { ID:'19' ,Term: 'Scriptting programming',  Description:' A scripting language is a programming language that employs a high-level construct to interpret and execute one command at a time', Reference: '“What is scripting language? - Definition from WhatIs.com,” WhatIs.com. https://www.techtarget.com/whatis/definition/scripting-language#:~:text=A%20scripting%20language%20is%20a‌' },
  { ID:'20' ,Term: 'IAC',  Description:'Infrastructure as code (IaC) is the process of managing and provisioning computer data centers through machine-readable definition files, rather than physical hardware configuration or interactive configuration tools', Reference: '“Infrastructure as code,” Wikipedia, Feb. 18, 2021. https://en.wikipedia.org/wiki/Infrastructure_as_code' },
  { ID:'21' ,Term: 'Cloud Native Apps',  Description:'The term cloud native refers to an application that was designed to reside in the cloud from the start. Cloud native involves cloud technologies like microservices, container orchestrators, and auto scaling', Reference: '“What is Cloud Native? - Everything you need to know - AWS,” Amazon Web Services, Inc. https://aws.amazon.com/what-is/cloud-native/#:~:text=The%20term%20cloud%20native%20refers"' },
  { ID:'22' ,Term: 'API Gateway',  Description:'An API gateway is a data-plane entry point for API calls that represent client requests to target applications and services', Reference: '“What Is an API Gateway? A Quick Learn Guide | NGINX Learning,” NGINX. https://www.nginx.com/learn/api-gateway/#:~:text=An%20API%20gateway%20is%20a%20data%2Dplane%20entry%20point%20for"'},
  { ID:'23' ,Term: 'Authentication',  Description:'term that refers to the process of proving that some fact or some document is genuine', Reference:'"https://auth0.com/intro-to-iam/what-is-authentication' },
  { ID:'24' ,Term: 'Authorization',  Description:'Authorization is the process of giving someone the ability to access a resource.', Reference: '“Infrastructure as code,” Wikipedia, Feb. 18, Authorization is the process of giving someone the ability to access a resource.', Reference:'“What is Authorization? - Examples and definition,” Auth0. https://auth0.com/intro-to-iam/what-is-authorization' },
  { ID:'25' ,Term: 'Catalogue',  Description:'The IT service catalog is a list of the IT services that an organization offers to its employees or customers. It allows users to research the services available to them in an organized, user-friendly interface, so they can send efficient, focused, and relevant requests to their IT colleagues', Reference: '“What is an IT Service Catalog? Definition, Examples - Freshservice,” www.freshworks.com. https://www.freshworks.com/freshservice/it-service-catalog/#:~:text=A%20deep%20dive- (accessed Sep. 20, 2023).' },
  { ID:'26' ,Term: 'Docker',  Description:'Docker is an open source platform that enables developers to build, deploy, run, update and manage containers', Reference: '“What is Docker? | IBM,” www.ibm.com. https://www.ibm.com/topics/docker#:~:text=Docker%20is%20an%20open%20source%20platform%20that%20enables%20developers%20to' },
  { ID:'27' ,Term: 'Docker compose',  Description:'Docker Compose is a tool that helps you define and share multi-container applications', Reference: '“Use Docker Compose,” Docker Documentation, May 12, 2022. https://docs.docker.com/get-started/08_using_compose/#:~:text=Docker%20Compose%20is%20a%20tool' },
  { ID:'28' ,Term: 'Multi container applications',  Description:'A multi-container application consists of multiple containers running at the same time.', Reference:'E. Njorge, “How to Deploy a Multi-Container Application to Kubernetes,” Sweetcode.io, Jan. 30, 2023. https://sweetcode.io/how-to-deploy-a-multi-container-application-to-kubernetes/#:~:text=In%20Application%20Development (accessed Sep. 20, 2023).'},
  { ID:'29' ,Term: 'Mongo DB',  Description:'MongoDB is a source-available cross-platform document-oriented database program. Classified as a NoSQL database program, MongoDB uses JSON-like documents with optional schemas', Reference: 'Wikipedia Contributors, “MongoDB,” Wikipedia, Oct. 31, 2019. https://en.wikipedia.org/wiki/MongoDB' },
  { ID:'30' ,Term: 'Azure storage',  Description:'The Azure Storage platform is Microsoft cloud storage solution for modern data storage scenarios', Reference:'tamram, “Introduction to Azure Storage - Cloud storage on Azure,” learn.microsoft.com, 2023. https://learn.microsoft.com/en-us/azure/storage/common/storage-introduction' },
  { ID:'31' ,Term: 'Volumes',  Description:'Volumes are the preferred mechanism for persisting data generated by and used by Docker containers.',Reference:'“Use volumes,” Docker Documentation, Jan. 04, 2019. https://docs.docker.com/storage/volumes/‌' },
  { ID:'32' ,Term: 'Bind mount',  Description:'Bind mounts have been around since the early days of Docker. Bind mounts have limited functionality compared to volumes. When you use a bind mount, a file or directory on the host machine is mounted into a container', Reference:'“Use bind mounts,” Docker Documentation, Jul. 28, 2020. https://docs.docker.com/storage/bind-mounts/' },
  { ID:'33' ,Term: 'tmpfs mount',  Description:'A temporary file system (TMPFS) uses local memory for file system reads and writes, which is typically much faster than reads and writes in a UFS file system. TMPFS file systems can improve system performance by saving the cost of reading and writing temporary files to a local disk or across the network', Reference:'“Creating a Temporary File System (TMPFS) - System Administration Guide: Devices and File Systems,” docs.oracle.com. https://docs.oracle.com/cd/E18752_01/html/817-5093/fscreate-99040.html#:~:text=A%20temporary%20file%20system%20(TMPFS)%20uses%20local%20memory%20for%20file (accessed Sep. 20, 2023).' },
  { ID:'34' ,Term: 'nodemon',  Description:' nodemon is a tool that helps develop Node. js based applications by automatically restarting the node application when file changes in the directory are detected', Reference:'“nodemon,” npm, Jul. 09, 2023. https://www.npmjs.com/package//nodemon (accessed Sep. 20, 2023).' },
  { ID:'35' ,Term: 'A bridge Network',  Description:'A bridge network is a Link Layer device which forwards traffic between network segments', Reference:'“Bridge network driver,” Docker Documentation, Aug. 22, 2023. https://docs.docker.com/network/drivers/bridge/#:~:text=In%20terms%20of%20networking%2C%20a (accessed Sep. 20, 2023).' },
  { ID:'36' ,Term: 'An overlay network',  Description:'An overlay network is a virtual or logical network that is created on top of an existing physical network', Reference:'“What is an overlay network?,” Networking. https://www.techtarget.com/searchnetworking/definition/overlay-network#:~:text=An%20overlay%20network%20is%20a (accessed Sep. 20, 2023).' },
  { ID:'37' ,Term: 'Synchronous commiunication',  Description:'Real-time communication where you can exchange information with others immediately.', Reference:'H. Amin, “5 Situations when synchronous communication is a must,” Hypercontext, Aug. 16, 2021. https://hypercontext.com/blog/communication/when-to-use-synchronous-communication#:~:text=Synchronous%20communication%20is%20real%2Dtime' },
  { ID:'38' ,Term: 'Asynchronous commiunication',  Description:'asynchronous communication is communication that does not happen in real-time e.g. on the phone, in-person, or during a live video conferencing meeting', Reference:'S. Barron, “What Is Asynchronous Communication & How Do You Use It?,” resources.owllabs.com. https://resources.owllabs.com/blog/asynchronous-communication#:~:text=Asynchronous%20Communication%20Definition&text=Simply%20put%2C%20asynchronous%20communication%20is' },
  { ID:'39' ,Term: 'A macvlan network',  Description:'Macvlan is a virtual LAN that you can use if you want to assign several IP addresses to the same network interface', Reference:'“Macvlan network,” LXD documentation. https://documentation.ubuntu.com/lxd/en/stable-5.0/reference/network_macvlan/ (accessed Sep. 20, 2023).' },
  { ID:'40' ,Term: 'one to one commiunication',  Description:'Information is exchanged between one source and one receiver', Reference:'“Which of the following is an example of one to one communication?,” byjus.com. https://byjus.com/question-answer/which-of-the-following-is-an-example-of-one-to-one-communication-telephonenewspaper-televisionradio/' },
  { ID:'41' ,Term: 'Kubernetes',  Description:'Kubernetes is an open-source container orchestration system for automating software deployment, scaling, and management',Reference:' “Kubernetes,” Wikipedia, May 11, 2020. https://en.wikipedia.org/wiki/Kubernetes '},
  { ID:'42' ,Term: 'Kube-proxy',  Description:'kube-proxy is a network proxy that runs on each node in your cluster, implementing part of the Kubernetes Service concept. kube-proxy maintains network rules on nodes.', Reference:'“Kubernetes Components,” Kubernetes. https://kubernetes.io/docs/concepts/overview/components/#:~:text=kube%2Dproxy%20is%20a%20network' },
  { ID:'43' ,Term: 'Container runtime',  Description:'Container runtime interface (CRI) is a plugin interface that lets the kubelet—an agent that runs on every node in a Kubernetes cluster—use more than one type of container runtime', Reference:'“Container Runtime Interface (CRI): Past, Present, and Future,” Aqua. https://www.aquasec.com/cloud-native-academy/container-security/container-runtime-interface/#:~:text=Container%20runtime%20interface%20(CRI)%20is (accessed Oct. 09, 2023).' },
  { ID:'44' ,Term: 'Terraform',  Description:'Terraform is an infrastructure-as-code software tool created by HashiCorp.', Reference:'“Terraform (software),” Wikipedia, Jul. 20, 2022. https://en.wikipedia.org/wiki/Terraform_(software)' },
  { ID:'45' ,Term: 'Regression Test',  Description:'Regression Testing is a type of testing in the software development cycle that runs after every change to ensure that the change introduces no unintended breaks.', Reference:'“Regression Testing : Definition, How it works,” BrowserStack. https://www.browserstack.com/guide/regression-testing#:~:text=Regression%20Testing%20is%20a%20type' },
  { ID:'46' ,Term: 'Security Test',  Description:'Security Testing is a type of Software Testing that uncovers vulnerabilities of the system and determines that the data and resources of the system are protected from possible intruders', Reference:'“Software Testing | Security Testing - GeeksforGeeks,” GeeksforGeeks, May 10, 2019. https://www.geeksforgeeks.org/software-testing-security-testing/' },
  { ID:'47' ,Term: 'FLUENTD',  Description:'Fluentd is a cross-platform open-source data collection software project originally developed at Treasure Data. It is written primarily in the Ruby programming language.', Reference:'“Fluentd,” Wikipedia, Mar. 23, 2022. https://en.wikipedia.org/wiki/Fluentd' },
  { ID:'48' ,Term: 'KIBANA',  Description:'Kibana provides visualization capabilities on top of the content indexed on an Elasticsearch cluster. Users can create bar, line and scatter plots, or pie charts and maps on top of large volumes of data', Reference:'“Kibana,” Wikipedia, May 10, 2022. https://en.wikipedia.org/wiki/Kibana' },
  { ID:'49' ,Term: 'PROMETHEUS',  Description:'Prometheus is a free software application used for event monitoring and alerting. It records metrics in a time series database (allowing for high dimensionality) built using an HTTP pull model, with flexible queries and real-time alerting', Reference:'“Prometheus (software),” Wikipedia, Apr. 29, 2020. https://en.wikipedia.org/wiki/Prometheus_(software)' },
  { ID:'50' ,Term: 'GRAFANA',  Description:'Grafana is a multi-platform open source analytics and interactive visualization web application. It provides charts, graphs, and alerts for the web when connected to supported data sources.', Reference:'“Grafana,” Wikipedia, Dec. 31, 2021. https://en.wikipedia.org/wiki/Grafanas ‌' },
];

router.get('/', (req, res, next) => {
  res.render('index', { title: 'DevOps Glossary', glossaryTerms });
});

module.exports = router;
